language: python
python: "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *.py
 - flake8  --max-complexity=10 --exclude=*.txt --max-line-length=180

script:
 - lettuce test/
 - python test/TestLogin.py -v
 - python test/TestAltasBajas.py -v
 - coverage run --branch test/TestLogin.py
 - coverage run --branch test/TestAltasBajas.py
 - coverage report -m

notifications: 
 email: false
