language: python
python: "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *
 - flake8 --ignore=F821,F401 --max-complexity=15 --exclude=*.txt,*.md,*.sikuli,*.jar --max-line-length=150 *
script:
 - lettuce test/
 - python test/TestLogin.py -v
 - python test/TestAltasBajas.py -v
 - coverage run --branch test/TestLogin.py
 - coverage run --branch test/TestAltasBajas.py
 - coverage report -m

notifications: 
 email: false
